### ISSUE TITLE
Does this library work?

### ISSUE THREAD

**Issue by AnthonyAchoy** [danielTobon43/sht1x_esp32_idf_library#1]
Hi!
I've been working with your library and I made a lot of improvements/changes to its logic and it is still not working. I think it is a timing issue but I'm not sure. Does this lib work for someone else?

**Comment by ghost** [comment]
Hi, why do you think it is not working? do you have some error? I used this library (that is basically the same arduino library but in C) and it worked for me. Could you please post picture of what are you doing?

Daniel

**Comment by AnthonyAchoy** [comment]
Hi, Daniel
Thank you for such a fast response. We are trying to implement sht10 sensor
with and ESP32. It was really hard to link cMakes at the beginning, but
after resolving that issue we decided to improve your program structure
(check them out below). The errors we get are mainly "not able to measure".
Also I attach our main program for you to look at.
 hello_world.tar.gz
<https://drive.google.com/a/lantern.tech/file/d/1H20Gkl6bViLh4PbCD3ngeDZD4KpLs3Br/view?usp=drive_web>

**Comment by AnthonyAchoy** [comment]
Also if you can help us on a call or something it would be greatly
appreciated. Just tell which application in case you want it, thanks!

**Comment by ghost** [comment]
Hi Anthony, how are you flashing the program to the esp32, are you using esp-idf? and I can't see the CMakeLists.txt file.

**Comment by ghost** [comment]
What I can see from your program is that you are using a python script to flash the program, right? if that is the case is difficult for me to help you since I made this library (just a translation in C) from the Arduino library to use with the ESP-IDF framework that is the framework for programming the esp32. On the other hand, I use CMake to define the project and then I flash the program with (idf.py). Now, if for you the way that you are defining your project works with another program so I recommend you to printf something in each line, so you can identify where is happening the problem.

**Comment by ghost** [comment]
I created my own project with your files and is working, although you are using the older library with the humidity fixed but is good. I can't see your error.

![Screenshot from 2020-01-10 10-24-49](https://user-images.githubusercontent.com/35694200/72146080-a3d3d780-3393-11ea-999f-26b4b13e394b.png)

**Comment by AnthonyAchoy** [comment]
Hi, Daniel,

We are actually compiling using idf and it is working pretty well. The
problem we are having is the same as the one you sent us in that
screenshot: "ack not received". Those values that you are receiving are the
default ones when nothing is connected. In our case, we are receiving those
ones when we have the sensor connected. What can you recommend doing to fix
the ack's and the measurement problem?

**Comment by ghost** [comment]
well, I noticed that there is a problem with the reading and I will check where is the problem (because the reading is always constant). According to your problem should be a hardware problem or configuration problem with the ACK pin, you should try to change the pin number to another location, maybe the pin number that you choose has an internal configuration for another purpose that is blocking the ACK signal to the sensor.

**Comment by AnthonyAchoy** [comment]
Thanks!

**Comment by ghost** [comment]
Hi @AnthonyAchoy, I made changes in the code that fix the problem with the temperature. Please let me know if everything is working well. I used data pin 27 and sck pin 2
